// Week 4 - Day 18b - Angular Routing & Forms/Exercises/03 - Nested Routes/solution/dashboard-layout.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-dashboard-layout',
  template: `
    <div style="display:flex; min-height:100vh;">
      <!-- Sidebar — this element stays rendered for all /dashboard/* routes -->
      <nav style="width:160px; background:#2c3e50; color:#fff; padding:1rem;">
        <h3 style="margin:0 0 1rem;">Dashboard</h3>
        <ul style="list-style:none; padding:0; margin:0;">
          <!-- routerLink="/dashboard" matches the empty '' child (OverviewComponent) -->
          <!-- [routerLinkActiveOptions]="{exact:true}" prevents /dashboard from
               being "active" on /dashboard/analytics as well -->
          <li>
            <a routerLink="/dashboard"
               routerLinkActive="active"
               [routerLinkActiveOptions]="{ exact: true }">Overview</a>
          </li>
          <li>
            <a routerLink="/dashboard/analytics"
               routerLinkActive="active">Analytics</a>
          </li>
          <li>
            <a routerLink="/dashboard/settings"
               routerLinkActive="active">Settings</a>
          </li>
        </ul>
      </nav>

      <!-- Child outlet — the matched child component renders here -->
      <main style="flex:1; padding:1.5rem;">
        <router-outlet></router-outlet>
      </main>
    </div>
  `,
  styles: [`
    a { display:block; color:#ccc; text-decoration:none; padding:0.4rem 0; }
    a.active { color:#fff; font-weight:bold; }
  `],
})
export class DashboardLayoutComponent {}

// Week 4 - Day 18a - React Routing & Redux/Exercises/03 - Nested Routes and Layouts/solution/layouts/DashboardLayout.jsx
// src/layouts/DashboardLayout.jsx  (solution)
import React from 'react';
import { NavLink, Outlet } from 'react-router-dom';

// Returns 'active' when the NavLink matches the current URL
const navLinkClass = ({ isActive }) => (isActive ? 'active' : '');

function DashboardLayout() {
  return (
    <div style={{ display: 'flex', minHeight: '100vh' }}>
      {/* Sidebar — stays mounted while child routes swap */}
      <aside style={{ width: '200px', background: '#f0f0f0', padding: '1rem', borderRight: '1px solid #ccc' }}>
        <h2>Dashboard</h2>
        <nav style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
          {/* `end` prevents /dashboard from matching /dashboard/analytics */}
          <NavLink to="/dashboard" end className={navLinkClass}>Overview</NavLink>
          <NavLink to="/dashboard/analytics" className={navLinkClass}>Analytics</NavLink>
          <NavLink to="/dashboard/settings" className={navLinkClass}>Settings</NavLink>
        </nav>
      </aside>

      {/* <Outlet /> renders the matched child route's element */}
      <main style={{ flex: 1, padding: '1rem' }}>
        <Outlet />
      </main>
    </div>
  );
}

export default DashboardLayout;
