// Week 4 - Day 18a - React Routing & Redux/Exercises/03 - Nested Routes and Layouts/starter-code/layouts/DashboardLayout.jsx
// src/layouts/DashboardLayout.jsx  (starter)
import React from 'react';
// TODO 2: Import NavLink and Outlet from 'react-router-dom'.

function DashboardLayout() {
  const navLinkClass = ({ isActive }) => (isActive ? 'active' : '');

  return (
    <div style={{ display: 'flex', minHeight: '100vh' }}>
      {/* Sidebar */}
      <aside style={{ width: '200px', background: '#f0f0f0', padding: '1rem' }}>
        <h2>Dashboard</h2>
        <nav style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
          {/* TODO 3: Add three <NavLink> elements with className={navLinkClass}:
                - "Overview"  → to="/dashboard"    (add end prop to prevent matching /dashboard/*)
                - "Analytics" → to="/dashboard/analytics"
                - "Settings"  → to="/dashboard/settings"
          */}
        </nav>
      </aside>

      {/* Main content area */}
      <main style={{ flex: 1, padding: '1rem' }}>
        {/* TODO 4: Render <Outlet /> here so child route content appears in this area */}
      </main>
    </div>
  );
}

export default DashboardLayout;

// Week 4 - Day 18b - Angular Routing & Forms/Exercises/03 - Nested Routes/starter-code/dashboard-layout.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-dashboard-layout',
  template: `
    <div style="display:flex; min-height:100vh;">
      <!-- Sidebar navigation — always visible while on /dashboard/* -->
      <nav style="width:160px; background:#2c3e50; color:#fff; padding:1rem;">
        <h3 style="margin:0 0 1rem;">Dashboard</h3>
        <!-- TODO 4 – Replace plain <a> tags with routerLink and add routerLinkActive="active" -->
        <ul style="list-style:none; padding:0; margin:0;">
          <li><a href="/dashboard">Overview</a></li>
          <li><a href="/dashboard/analytics">Analytics</a></li>
          <li><a href="/dashboard/settings">Settings</a></li>
        </ul>
      </nav>

      <!-- Main content area — child components render here -->
      <main style="flex:1; padding:1.5rem;">
        <!-- TODO 5 – Add <router-outlet> so child routes are projected into this area -->
      </main>
    </div>
  `,
  styles: [`
    a { display:block; color:#ccc; text-decoration:none; padding:0.4rem 0; }
    a.active { color:#fff; font-weight:bold; }
  `],
})
export class DashboardLayoutComponent {}
